name: Python Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install telebot pymongo aiohttp
          pip install python-telegram-bot pyTelegramBotAPI certifi

      - name: Set Execute Permissions
        run: |
          chmod +x * 
          chmod +x bgmi

      - name: Show Binary and Python File Name
        run: |
          echo "Binary Name: bgmi"
          echo "Python File Name: r.py"

      - name: Run Application
        run: python r.py
